spring.application.name=vehiculos-api
spring.data.mongodb.uri=mongodb+srv://felipe_db_vehiculos:f2025password_db_vh@cluster0.gaodo1w.mongodb.net/?appName=VehiculosDB
spring.data.mongodb.database=vehiculosDB

